package com.bonnyfone.vectalign.techniques;

import android.support.v7.graphics.drawable.PathParser;

import java.util.ArrayList;

/**
 * This class represents the technique used to fill the (eventual) holes generated by the sequence alignment.
 */
public abstract class AbstractFillMode {

    public abstract void fillInjectedNodes(ArrayList<PathParser.PathDataNode> from, ArrayList<PathParser.PathDataNode> to);

}
